-- ============================================================
-- SCRIPT DE CRIAÇÃO DA TABELA COMPLETA: GASCTPNA_matricula
-- Compatível com Supabase / PostgreSQL (Todos os campos de texto como TEXT)
-- Mapeia 100% dos campos do formulário matricula_aluno.html + campo TURMA
-- ============================================================

CREATE TABLE IF NOT EXISTS "GASCTPNA_matricula" (
    -- 1. IDENTIFICAÇÃO DO REGISTRO E CONTROLE
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL DEFAULT 'pendente', -- pendente, validada, inativa, excluida
    "origem_cadastro" TEXT DEFAULT 'Portal do Aluno',
    "validation_token" TEXT DEFAULT NULL,

    -- 2. IDs DE RELACIONAMENTO (CHAVES ESTRANGEIRAS / ÍNDICES)
    "projeto_id" INT DEFAULT NULL REFERENCES "GASCTPNA_projetos"("id") ON DELETE SET NULL,
    "cidade_id" INT DEFAULT NULL REFERENCES "GASCTPNA_cidades"("id") ON DELETE SET NULL,
    "bairro_id" INT DEFAULT NULL REFERENCES "GASCTPNA_bairros"("id") ON DELETE SET NULL,
    "modalidade_id" INT DEFAULT NULL REFERENCES "GASCTPNA_modalidades"("id") ON DELETE SET NULL,
    "nucleo_id" INT DEFAULT NULL REFERENCES "GASCTPNA_nucleos"("id") ON DELETE SET NULL,
    "portal_usuario_id" INT DEFAULT NULL,

    -- 3. ALOCAÇÃO (TURMA & TURNO)
    "turma" TEXT DEFAULT NULL, -- Campo definido via n8n para alocação do aluno em turma
    "turno" TEXT DEFAULT NULL, -- Manhã, Tarde, Noite

    -- 4. DADOS DE IDENTIFICAÇÃO DO ALUNO (ETAPAS 1 e 2)
    "aluno_cpf" TEXT NOT NULL,
    "aluno_nome" TEXT NOT NULL,
    "chk_usar_nome_social" BOOLEAN DEFAULT FALSE,
    "nome_social" TEXT DEFAULT NULL,
    "data_nascimento" DATE DEFAULT NULL,
    "sexo" TEXT DEFAULT NULL, -- Masculino, Feminino
    "idade" INT DEFAULT NULL,

    -- 5. MEDIDAS E UNIFORME (ETAPA 6)
    "altura" INT DEFAULT NULL, -- em cm (ex: 170)
    "peso" NUMERIC(5,2) DEFAULT NULL, -- em kg (ex: 62.50)
    "tamanho_calcado" TEXT DEFAULT NULL, -- ex: 34, 36, 38, 40, 42, 44, 46
    "tamanho_camisa" TEXT DEFAULT NULL, -- ex: 10, 14, M, GG
    "tamanho_calca" TEXT DEFAULT NULL, -- tamanho da bermuda/calça (ex: 36, 38, 40)

    -- 6. DADOS PERSONAIS E ACADÊMICOS COMPLEMENTARES (ETAPA 6)
    "raca" TEXT DEFAULT NULL, -- Negra, Branca, Parda, Amarela, Indígena
    "naturalidade" TEXT DEFAULT NULL, -- Cidade natal (ex: Niterói - RJ)
    "escolaridade" TEXT DEFAULT NULL, -- Ensino Fundamental, Ensino Médio, Graduação, Pós-graduação

    -- 7. ENDEREÇO RESIDENCIAL DO ALUNO (ETAPA 7)
    "cep" TEXT DEFAULT NULL,
    "endereco" TEXT DEFAULT NULL, -- Logradouro / Rua / Av.
    "numero" TEXT DEFAULT NULL,
    "complemento" TEXT DEFAULT NULL,
    "bairro" TEXT DEFAULT NULL, -- Nome do bairro do endereço
    "cidade" TEXT DEFAULT NULL, -- Nome da cidade do endereço
    "uf" TEXT DEFAULT NULL,

    -- 8. SITUAÇÃO SOCIOECONÔMICA E CONTATO DO ALUNO (ETAPA 7)
    "faixa_salarial" TEXT DEFAULT NULL, -- Até 1 SM, De 1SM a 3SM, De 3SM a 5SM, Acima de 5SM
    "whatsapp" TEXT DEFAULT NULL, -- Contato principal do aluno
    "profissao" TEXT DEFAULT NULL,
    "email" TEXT DEFAULT NULL,

    -- 9. DADOS DO RESPONSÁVEL LEGAL (ETAPA 8 - Obrigatório para menores de idade)
    "resp_cpf" TEXT DEFAULT NULL,
    "resp_nome" TEXT DEFAULT NULL,
    "resp_nome_social" TEXT DEFAULT NULL,
    "resp_data_nasc" DATE DEFAULT NULL,
    "resp_sexo" TEXT DEFAULT NULL,
    "resp_raca" TEXT DEFAULT NULL,
    "resp_email" TEXT DEFAULT NULL,
    "resp_whatsapp" TEXT DEFAULT NULL,
    "resp_escolaridade" TEXT DEFAULT NULL,
    "resp_profissao" TEXT DEFAULT NULL,

    -- 10. QUESTIONÁRIO DE SAÚDE (ETAPA 9 - Perguntas 1 a 6 + Detalhes)
    "uso_medicacao" TEXT DEFAULT NULL, -- Sim / Nao
    "uso_medicacao_detalhes" TEXT DEFAULT NULL,

    "possui_alergias" TEXT DEFAULT NULL, -- Sim / Nao
    "possui_alergias_detalhes" TEXT DEFAULT NULL,

    "plano_saude" TEXT DEFAULT NULL, -- Sim / Nao
    "plano_saude_detalhes" TEXT DEFAULT NULL,

    "acompan_medico" TEXT DEFAULT NULL, -- Sim / Nao
    "acompan_medico_detalhes" TEXT DEFAULT NULL,

    "restricao_fisica" TEXT DEFAULT NULL, -- Sim / Nao
    "restricao_fisica_detalhes" TEXT DEFAULT NULL,

    "necessidade_especial" TEXT DEFAULT NULL, -- Sim / Nao
    "necessidade_especial_detalhes" TEXT DEFAULT NULL,

    -- 11. DOCUMENTOS / LAUDOS ANEXADOS (ETAPA 9)
    "deseja_laudo" TEXT DEFAULT NULL, -- Sim / Nao
    "documentos_urls" TEXT DEFAULT NULL, -- URLs dos documentos/laudos salvos pelo n8n

    -- 12. REDES SOCIAIS (ETAPA 9)
    "rede_social_tipo" TEXT DEFAULT NULL, -- Instagram, TikTok, Facebook, YouTube, X
    "rede_social_link" TEXT DEFAULT NULL,
    "instagram" TEXT DEFAULT NULL,
    "tiktok" TEXT DEFAULT NULL,
    "facebook" TEXT DEFAULT NULL,
    "youtube" TEXT DEFAULT NULL,
    "twitter_x" TEXT DEFAULT NULL,

    -- 13. TERMOS, LGPD E DECLARAÇÃO DE VERACIDADE (ETAPA 10)
    "lgpd_aceite" BOOLEAN NOT NULL DEFAULT FALSE,
    "lgpd_aceite_em" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    "lgpd_versao" TEXT DEFAULT 'v1',
    "aceite_veracidade" BOOLEAN NOT NULL DEFAULT FALSE,
    "aceite_veracidade_em" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    "aceite_veracidade_versao" TEXT DEFAULT 'v1'
);

-- ============================================================
-- ÍNDICES DE PERFORMANCE E CONSULTAS RÁPIDAS NO N8N / DASHBOARD
-- ============================================================
CREATE INDEX IF NOT EXISTS "idx_gasctpna_mat_cpf" ON "GASCTPNA_matricula" ("aluno_cpf");
CREATE INDEX IF NOT EXISTS "idx_gasctpna_mat_projeto" ON "GASCTPNA_matricula" ("projeto_id");
CREATE INDEX IF NOT EXISTS "idx_gasctpna_mat_cidade" ON "GASCTPNA_matricula" ("cidade_id");
CREATE INDEX IF NOT EXISTS "idx_gasctpna_mat_bairro" ON "GASCTPNA_matricula" ("bairro_id");
CREATE INDEX IF NOT EXISTS "idx_gasctpna_mat_modalidade" ON "GASCTPNA_matricula" ("modalidade_id");
CREATE INDEX IF NOT EXISTS "idx_gasctpna_mat_nucleo" ON "GASCTPNA_matricula" ("nucleo_id");
CREATE INDEX IF NOT EXISTS "idx_gasctpna_mat_turma" ON "GASCTPNA_matricula" ("turma");
CREATE INDEX IF NOT EXISTS "idx_gasctpna_mat_status" ON "GASCTPNA_matricula" ("status");
